function InitGlobals()
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(0), true)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(1), true)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(2), true)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(3), true)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(4), true)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(5), true)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(6), 6)
ForcePlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(6), true)
SetPlayerController(Player(6), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(7), 7)
ForcePlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(7), true)
SetPlayerController(Player(7), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(8), 8)
ForcePlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_RANDOM)
SetPlayerRaceSelectable(Player(8), true)
SetPlayerController(Player(8), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(12), 12)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(12), false)
SetPlayerController(Player(12), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(13), 13)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(13), false)
SetPlayerController(Player(13), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(14), 14)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(14), false)
SetPlayerController(Player(14), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(15), 15)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(15), false)
SetPlayerController(Player(15), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(16), 16)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_NEUTRAL)
SetPlayerStartLocation(Player(17), 17)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_UNDEAD)
SetPlayerRaceSelectable(Player(17), false)
SetPlayerController(Player(17), MAP_CONTROL_NEUTRAL)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerTeam(Player(1), 0)
SetPlayerTeam(Player(2), 0)
SetPlayerTeam(Player(3), 0)
SetPlayerTeam(Player(4), 0)
SetPlayerTeam(Player(5), 0)
SetPlayerTeam(Player(6), 0)
SetPlayerTeam(Player(7), 0)
SetPlayerTeam(Player(8), 0)
SetPlayerTeam(Player(9), 1)
SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(10), 1)
SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(11), 1)
SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(12), 1)
SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(13), 1)
SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(14), 1)
SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(15), 1)
SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(16), 1)
SetPlayerState(Player(16), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerTeam(Player(17), 1)
SetPlayerState(Player(17), PLAYER_STATE_ALLIED_VICTORY, 1)
SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(9), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(10), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(11), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(12), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(13), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(14), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(16), true)
SetPlayerAllianceStateAllyBJ(Player(15), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(16), Player(17), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(9), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(10), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(11), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(12), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(13), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(14), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(15), true)
SetPlayerAllianceStateAllyBJ(Player(17), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(9), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(10), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(11), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(12), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(13), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(14), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(16), true)
SetPlayerAllianceStateVisionBJ(Player(15), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(16), Player(17), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(9), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(10), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(11), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(12), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(13), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(14), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(15), true)
SetPlayerAllianceStateVisionBJ(Player(17), Player(16), true)
end

function InitAllyPriorities()
SetStartLocPrioCount(9, 7)
SetStartLocPrio(9, 0, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 1, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 2, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 3, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 4, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 5, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(9, 3)
SetEnemyStartLocPrio(9, 0, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 1, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 2, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(10, 2)
SetStartLocPrio(10, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(11, 5)
SetStartLocPrio(11, 0, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 1, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 2, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 3, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 4, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(11, 10)
SetEnemyStartLocPrio(11, 0, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 1, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 2, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 3, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 4, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 5, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 6, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 7, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 8, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(12, 3)
SetStartLocPrio(12, 0, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(12, 1, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(12, 2, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(12, 2)
SetEnemyStartLocPrio(12, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(13, 2)
SetStartLocPrio(13, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 1, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(13, 9)
SetEnemyStartLocPrio(13, 0, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 1, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 2, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 3, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 4, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 5, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 6, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 7, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 8, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(14, 2)
SetStartLocPrio(14, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(14, 9)
SetEnemyStartLocPrio(14, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 2, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 3, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 4, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 5, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 6, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 7, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(15, 3)
SetStartLocPrio(15, 0, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 1, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 2, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(15, 2)
SetEnemyStartLocPrio(15, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 1, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(16, 10)
SetStartLocPrio(16, 0, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 1, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 2, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 3, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 4, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 5, 10, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 6, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 7, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 8, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 9, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(16, 8)
SetEnemyStartLocPrio(16, 0, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 2, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 3, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(16, 4, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 5, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 6, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 7, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(17, 1)
SetStartLocPrio(17, 0, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(17, 10)
SetEnemyStartLocPrio(17, 0, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 1, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 2, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 3, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 4, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 5, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 6, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 7, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 8, 15, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-15616.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -15872.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 15616.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 15360.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -15616.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 15360.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 15616.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -15872.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
SetTerrainFogEx(0, 3000.0, 5000.0, 0.500, 1.000, 0.000, 0.000)
SetWaterBaseColor(255, 0, 0, 255)
NewSoundEnvironment("Default")
SetAmbientDaySound("LordaeronSummerDay")
SetAmbientNightSound("LordaeronSummerNight")
SetMapMusic("Music", true, 0)
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_011")
SetMapDescription("TRIGSTR_013")
SetPlayers(18)
SetTeams(18)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, -10368.0, 10112.0)
DefineStartLocation(1, -128.0, 10112.0)
DefineStartLocation(2, 10368.0, 10112.0)
DefineStartLocation(3, -10368.0, -256.0)
DefineStartLocation(4, 0.0, -256.0)
DefineStartLocation(5, 10368.0, -256.0)
DefineStartLocation(6, -10368.0, -10624.0)
DefineStartLocation(7, 0.0, -10624.0)
DefineStartLocation(8, 10368.0, -10624.0)
DefineStartLocation(9, -10368.0, 10112.0)
DefineStartLocation(10, -128.0, 10112.0)
DefineStartLocation(11, 10368.0, 10112.0)
DefineStartLocation(12, -10368.0, -256.0)
DefineStartLocation(13, 0.0, -256.0)
DefineStartLocation(14, 10368.0, -256.0)
DefineStartLocation(15, -10368.0, -10624.0)
DefineStartLocation(16, 0.0, -10624.0)
DefineStartLocation(17, 10368.0, -10624.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

